[toolchain]
anchor_version = "0.32.1"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
batch_sigverify = "2o1R3JBBaY39F6zRMyKpfZhFq88bEARA1b2bbUe39tVo"

[programs.devnet]
batch_sigverify = "2o1R3JBBaY39F6zRMyKpfZhFq88bEARA1b2bbUe39tVo"

[programs.mainnet]
batch_sigverify = "2o1R3JBBaY39F6zRMyKpfZhFq88bEARA1b2bbUe39tVo"

[registry]
url = "https://api.github.com/repos/coral-xyz/anchor"

[test]
startup_wait = 5000
shutdown_wait = 2000
