[toolchain]
anchor_version = "0.29.0"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
batch_sigverify = "4vH2fvTbfgtSwS4nNzUEfHXVRFhXKjhPiEmF9RXd3bVx"

[programs.devnet]
batch_sigverify = "4vH2fvTbfgtSwS4nNzUEfHXVRFhXKjhPiEmF9RXd3bVx"

[programs.mainnet]
batch_sigverify = "4vH2fvTbfgtSwS4nNzUEfHXVRFhXKjhPiEmF9RXd3bVx"

[registry]
url = "https://api.github.com/repos/coral-xyz/anchor"

[test]
startup_wait = 5000
shutdown_wait = 2000
